[FE] TechChip 컴포넌트 구현, index signiture 삭제, 스토리북 정상화
woowacourse-teams/2021-nolto pull request #143
Opened 2021-07-17 07:02 UTC by 0307kwon

## 작업 내용
- TechChip 컴포넌트 구현,
- index signiture 삭제
- 스토리북 정상화

Closes #142 

## 스크린샷
![image](https://user-images.githubusercontent.com/48755175/126028939-16bf4cb0-585b-4f28-a7f9-e8dd7ba51229.png)
![image](https://user-images.githubusercontent.com/48755175/126028945-43c2ad6a-5358-457c-8bb8-42617c7f313e.png)
![image](https://user-images.githubusercontent.com/48755175/126028957-4cefd2a5-7ff6-40a1-9a55-299d310b12a1.png)

## 주의사항
귀염뽀짝함

2021-07-17 07:24 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +import useUploadFeed from 'hooks/queries/useUploadFeed';
오 굿굿

2021-07-17 07:24 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +  const mutation = useUploadFeed();
여기는 왜 `mutation`으로 다시 돌리셨나요?

2021-07-17 07:24 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +
분리한거 조읍니당

2021-07-17 14:33 UTC, zigsong requested changes

2021-07-17 14:33 UTC, zigsong commented on frontend/.vscode/extensions.json
> +}
이게 왜 올라왔지요?

2021-07-17 16:57 UTC, 0307kwon commented on frontend/src/pages/Upload/Upload.tsx
> +  const mutation = useUploadFeed();
요고 uploadFeeds라는 이름이 바로 밑에 함수 uploadFeed랑 이름이 너무 겹쳐용!
그래서 일단 mutation으로 돌리긴 했는데 나중에 생각해보니 너무 일반적인 이름이라
uploadMutation으로 수정했는데 괜찮을까염 😊

2021-07-17 16:59 UTC, 0307kwon commented
피드백 반영했습니다! 확인해주세용~ ✨

2021-07-17 16:59 UTC, 0307kwon commented on frontend/.vscode/extensions.json
> +}
헉 뭐야 무서워요 바로 삭-제 👍

2021-07-18 02:43 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +  const mutation = useUploadFeed();
좋읍니닷

2021-07-18 02:44 UTC, zigsong commented
피드백 반영 감사합니다~~! 머지할게용

2021-07-18 02:44 UTC, merged