[FE] Upload 페이지 최소 구현 기능 완료
woowacourse-teams/2021-nolto pull request #145
Opened 2021-07-17 13:44 UTC by 0307kwon

## 작업 내용
작업하다보니 기능들이 너무 밀접해서 PR을 따로 나누지 못했습니다 ㅠㅜ
뒤늦게 깨닫고 나누려고 했지만 너무 관계가 밀접해서 나누지 못했습니다
PR이 너무 커진점... 반성하겠습니다 😭

추가된 대략적인 기능들
- validation
- redirection
- svg에 fill 속성으로 색을 변경할 수 있도록 수정
- UploadFeed 타이핑도 다시 살짝 수정하였습니다.

Closes #144 

## 스크린샷
![GIF 2021-07-17 오후 10-40-36](https://user-images.githubusercontent.com/48755175/126038956-dc05a670-3750-40ac-91b3-aa6a16993168.gif)

## 주의사항
이쁨

근데 문제점이 2가지 있습니다.
1. text area에 개행을 넣으면 게시물 등록이 안됩니다.
2. 대표 이미지는 옵셔널 아니었나용? 지금 대표 이미지가 없으면 등록이 안됩니다.

2021-07-17 14:48 UTC, zigsong requested changes
진짜 고생했군요 믹히... 
코드에 뭔가 특이한(?) 부분들은 설명을 달아주면 좋을 것 같아요!
간단간단한 수정 내용들과 제 질문들이 있답니다 
즐거운 밤.......... 🌝

2021-07-17 14:48 UTC, zigsong commented on frontend/.storybook/preview.js
> +        <ModalProvider>{story()}</ModalProvider>
#143 커밋에서 했는데 여기서 또한듯? 머지가 안됐어가지고 그런가염

2021-07-17 14:48 UTC, zigsong commented on frontend/.vscode/extensions.json
> +}
이게 왜 올라왔지요?

2021-07-17 14:48 UTC, zigsong commented on frontend/custom.d.ts
> +  const content: ({ fill, width }: SVGProps) => JSX.Element;
색상 채우는 용도인가요? 대박

2021-07-17 14:48 UTC, zigsong commented on frontend/src/components/@common/ErrorMessage/ErrorMessage.styles.ts
> +`;
에러 메시지 커스텀 진짜 광기

2021-07-17 14:48 UTC, zigsong commented on frontend/src/components/@common/ErrorMessage/ErrorMessage.tsx
> +  }
이렇게 컴포넌트 분리한거 넘모 좋아유 🍻

2021-07-17 14:48 UTC, zigsong commented on frontend/src/components/@common/ErrorMessage/ErrorMessage.tsx
> +        <span>{`${targetError.message}`}</span>
```suggestion
        <span>{targetError.message}</span>
```
그냥 이렇게 써도 되지 않을까요?

2021-07-17 14:48 UTC, zigsong commented on frontend/src/constants/message.ts
> +};
대박 깜찍함 미키 이런 사람이었어요?

2021-07-17 14:48 UTC, zigsong commented on frontend/src/pages/Home/Home.styles.ts
> +const MainSearchBar = styled(Searchbar)`
이 부분은 참고로 제 리팩토링 부분에

`export const Searchbar = styled(SearchbarComponent)`로 바꿨으니 나중에 resolve conflict 시 참고 baram...

2021-07-17 14:48 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +    shouldUnregister: true,
`shouldUnregister` 이거는 어떤 용도인가요?
[출처](https://github.com/react-hook-form/react-hook-form/releases/tag/v6.0.0-rc.4)  신기능이라 그런지 잘 설명이 안 나와있는 듯..?!

`watchStep`에 따라 특정 input이 가려지거나 생겼을 때, 해당 input에 입력됐던 값들을 보존하기 위함인가요?

2021-07-17 14:48 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +    }
인라인으로 해주세용~!

2021-07-17 14:48 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +                      message: UPLOAD_VALIDATION_MSG.INVALID_URL,
이것은 `urlRegex` 정도로 상수화(현재 파일 상단에)하는 게 어떨까요?

2021-07-17 14:48 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +                    message: UPLOAD_VALIDATION_MSG.INVALID_URL,
요기도 상수화

2021-07-17 14:48 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
>              <StyledButton buttonStyle={ButtonStyle.SOLID}>등록</StyledButton>
등록 버튼에 따로 `onClick` 등의 이름으로 POST 요청 보내는 핸들러가 안 붙어도 되나요? 
지금은 form 다 입력하고 enter 쳤을 때 전송이 되나요? (안될 것 같은디)

++ 혹시 POST 전송하고 에러 처리, 리다이렉트 등의 문제 때문에 잠시 보류해놓은 건가용?

2021-07-17 17:01 UTC, 0307kwon commented on frontend/.storybook/preview.js
> +        <ModalProvider>{story()}</ModalProvider>
이거 일단 #143 머지시키고 충돌나는지 확인해봐야할거같아요!
다 저의 불찰.... 🙇

2021-07-17 17:02 UTC, 0307kwon commented on frontend/.vscode/extensions.json
> +}
#143 에서 삭제하였습니닷! ✨

2021-07-17 17:03 UTC, 0307kwon commented on frontend/custom.d.ts
> +  const content: ({ fill, width }: SVGProps) => JSX.Element;
이제 우리 svg 컬러도 바꿀수 있어여 대박~ 🎉

2021-07-17 17:04 UTC, 0307kwon commented on frontend/src/components/@common/ErrorMessage/ErrorMessage.styles.ts
> +`;
ㅋㅋㅋㅋㅋ 디자인 감각이 없어서 힘들었습니다... 🤣

2021-07-17 17:04 UTC, 0307kwon commented on frontend/src/components/@common/ErrorMessage/ErrorMessage.tsx
> +        <span>{`${targetError.message}`}</span>
머야 지그 천재네요 👍👍

2021-07-17 17:05 UTC, 0307kwon commented on frontend/src/constants/message.ts
> +};
숨겨둔 Toy 함을 꺼냈습니다 👍

2021-07-17 17:08 UTC, 0307kwon commented on frontend/src/pages/Home/Home.styles.ts
> +const MainSearchBar = styled(Searchbar)`
라져댓

2021-07-17 17:10 UTC, 0307kwon commented on frontend/src/pages/Upload/Upload.tsx
> +    shouldUnregister: true,
넹 이거 step 선택할때 `진행중` 선택하면 배포 URL input 사라지잖아용
근데 form 데이터에 URL input value가 남아있는 경우가 있어가지고
요걸로 처리를 해줬습니다. 요고 해주면 사라져요. 편-안~ 🎉

2021-07-17 17:15 UTC, 0307kwon commented on frontend/src/pages/Upload/Upload.tsx
> +                      message: UPLOAD_VALIDATION_MSG.INVALID_URL,
상수같아서 `URL_REGEX` 스네이크 케이스로 선언 해주었습니다! ✨

2021-07-17 17:17 UTC, 0307kwon commented on frontend/src/pages/Upload/Upload.tsx
>              <StyledButton buttonStyle={ButtonStyle.SOLID}>등록</StyledButton>
버튼 type이 submit이라 onClick이 따로 없어도 form의 onSubmit이 발동이 됩니다!
지금 정상적으로 작동하고 있어용 👍👍

2021-07-17 17:17 UTC, 0307kwon commented on frontend/src/components/@common/ErrorMessage/ErrorMessage.tsx
> +  }
예에~ ✨

2021-07-18 02:44 UTC, zigsong commented on frontend/custom.d.ts
> +  const content: ({ fill, width }: SVGProps) => JSX.Element;
미쳤다뤼

2021-07-18 02:45 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
> +    shouldUnregister: true,
아하 최고네요 고생했어요!!!

2021-07-18 02:46 UTC, zigsong commented on frontend/src/pages/Upload/Upload.tsx
>              <StyledButton buttonStyle={ButtonStyle.SOLID}>등록</StyledButton>
아 그르네요 제가 착각했슴다 좋아용~~!

2021-07-18 02:47 UTC, zigsong commented
피드백 반영 수고하셨습니다!!
지금은 out-of-date를 해결해야 할 것 같아요~!

2021-07-18 05:28 UTC, merged