[FE] 검색옵션 추가, 검색 기능 구현
woowacourse-teams/2021-nolto pull request #223
Opened 2021-07-25 04:52 UTC by zigsong

## 작업 내용

Closes #217

- 검색옵션 추가
- 검색 기능 구현

## 스크린샷
![search](https://media.giphy.com/media/x7eOtofbY73NVIj7oJ/giphy.gif)

## 주의사항
- 검색창이 스무스하게 열리는 transition 아직 구현하지 못함 (잘 안 됨...)

2021-07-25 05:19 UTC, zigsong reviewed
검색 기능을 구현해보았습니당.

2021-07-25 05:19 UTC, zigsong commented on frontend/src/components/SearchBar/SearchBar.tsx
> +interface Props extends InputHTMLAttributes<HTMLInputElement> {
placeholder를 넣어주기 위해

2021-07-25 05:19 UTC, zigsong commented on frontend/src/components/SearchBar/SearchBar.tsx
> +  }, [searchType]);
검색옵션을 '제목/내용'으로 해놓고 input에 입력 후
검색옵션을 '기술태그'로 변경 시 기존의 '제목/내용' input이 남아 있어서 올바른 검색 쿼리를 만들지 못하는 문제

-> 검색옵션 변경 시마다 query를 초기화해줌

2021-07-25 05:19 UTC, zigsong commented on frontend/src/components/SearchBar/SearchBar.tsx
> +    </Styled.SelectedChips>
![image](https://user-images.githubusercontent.com/44080404/126888517-1c158054-87bb-436f-8dc3-000806de75e6.png)
검색옵션 '기술스택' 선택 시 상단에 뜨는 내용

2021-07-25 05:19 UTC, zigsong commented on frontend/src/components/SearchBar/SearchBar.tsx
> +        )}
`searchType`이 있다면 (따로 고려해주지 않아도) 당연히 이미 `selectable = true`라고 생각

2021-07-25 05:19 UTC, zigsong commented on frontend/src/context/techTag/input/TechInput.tsx
> +interface Props extends InputHTMLAttributes<HTMLInputElement> {
input에 placeholder를 넣어주기 위함

2021-07-25 05:19 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +  const techs = params.get('techs');
URL의 queryString을 가져오는 과정

2021-07-25 13:15 UTC, zigsong reviewed
아직 버그가 많음

2021-07-25 13:15 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +  const [techs, setTechs] = useState<Tech[]>(location.state?.techs);
설명이 따로 필요한 부분...

2021-07-25 13:15 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +  };
'제목/내용'으로 검색한 검색결과 페이지에서 다시 새로운  '제목/내용'으로 검색했을 경우

2021-07-25 13:15 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +  }, [techs]);
'기술스택'으로 검색한 검색결과 페이지에서 다시 새로운 '기술스택'으로 검색했을 경우

태그를 하나 추가/삭제할 때마다 바로 결과를 불러옴

2021-07-26 06:21 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +  }, [location.search]);
이미 검색결과창(`SearchResult`)에 있을 때 다시 `history.push`로 검색창을 띄우려고 하면 실패함 (같은 route로 push 불가)
그래서 query string(`location.search`)가 변화했음을 인지하고 그때마다 새로운 검색 쿼리를 날려줘야 함!

2021-07-27 00:16 UTC, zigsong reviewed
대규모 공사가 발생했습니다..~

2021-07-27 00:16 UTC, zigsong commented on frontend/src/components/SearchResultHeader/SearchResultHeader.tsx
> +  };
검색 결과 페이지 내에서 '제목/내용'으로 재검색할 때

2021-07-27 00:16 UTC, zigsong commented on frontend/src/components/SearchResultHeader/SearchResultHeader.tsx
> +  };
검색 결과 페이지 내에서 '기술스택'으로 재검색할 때

2021-07-27 00:16 UTC, zigsong commented on frontend/src/components/SearchResultHeader/SearchResultHeader.tsx
> +  }, [searchParams]);
`searchParams`는 부모 컴포넌트 (`SearchResult` 페이지)에서 내려준 `location.search`
즉 검색 또는 재검색으로 인해 url query string이 바뀔 때마다 새로운 `query`(제목/내용)와 `techs`(기술스택) 문자열을 받아서 다시 검색을 요청함

2021-07-27 00:16 UTC, zigsong commented on frontend/src/components/SearchResultHeader/SearchResultHeader.tsx
> +  const [queryValue, setQueryValue] = useState('');
'제목/내용'으로 재검색 시 검색창 form submit 전 검색창에 잠시 담아둘 (input의 `onChange`) query

2021-07-27 00:16 UTC, zigsong commented on frontend/src/hooks/queries/useAutoComplete.ts
> +}
기존에 `useTech`로 쓰이던 부분

2021-07-27 00:16 UTC, zigsong commented on frontend/src/pages/Home/Home.tsx
> +
![image](https://user-images.githubusercontent.com/44080404/127075184-203036b7-4a96-4835-8eb7-a810a5aebd6b.png)

2021-07-27 00:16 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +        </AsyncBoundary>
검색결과 창에서 재검색하는 검색창 부분

2021-07-27 00:16 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +          </AsyncBoundary>
검색결과 창에서 실제 검색 결과 (피드 목록)

2021-07-27 03:12 UTC, 0307kwon requested changes
검색이라는 막중한 임무를 잘 수행해주셨네요...!!! ✨🎉
네이밍 관련 부분 몇가지만 봐주시면 머지하겠습니닷 😊

2021-07-27 03:12 UTC, 0307kwon commented on frontend/src/components/SearchResultHeader/SearchResultHeader.tsx
> +  }, [searchParams]);
멋져용! 💯💯

2021-07-27 03:12 UTC, 0307kwon commented on frontend/src/hooks/queries/useAutoComplete.ts
> +}
useAutoComplete 네이밍 조금 구체화되었으면 좋겠습니닷...!! 😁

2021-07-27 03:12 UTC, 0307kwon commented on frontend/src/pages/Home/Home.tsx
> +const tags: Tech[] = [
ㅋㅋㅋㅋ 일단은 const로 들어가 있군용 🤣

2021-07-27 03:12 UTC, 0307kwon commented on frontend/src/pages/Home/Home.tsx
> +
댑악 이쁘다 ✨

2021-07-27 03:12 UTC, 0307kwon commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +          </AsyncBoundary>
SearchResult 컴포넌트 깔끔하네요...! 💯

2021-07-27 05:38 UTC, zigsong commented on frontend/src/components/SearchResultContent/SearchResultContent.tsx
> +  const { data: feeds } = useSearch({ query, techs }, { suspense: false });
검색결과 창 내에서 재검색 시 너무 로딩이 자주 깜박이는 문제가 있어서, 눈이 피로해서 끄는 게 좋겠다고 판단!

2021-07-27 10:22 UTC, merged