[FE] refactor: 메인 페이지 UI 개편
woowacourse-teams/2021-nolto pull request #490
Opened 2021-08-31 10:11 UTC by 0307kwon

## 작업 내용

메인 페이지 UI를 개편하였습니다~! 

Closes #489

## 스크린샷
![image](https://user-images.githubusercontent.com/48755175/131484726-6e2e6861-d7dc-4854-8e34-e9293208303b.png)

## 주의사항

2021-08-31 10:28 UTC, 0307kwon reviewed
주요한 부분에 코멘트 달았습니다~! ✨

2021-08-31 10:28 UTC, 0307kwon commented on frontend/src/App.tsx
> -                <main>
main 태그는 baseLayout으로 넣었습니다

2021-08-31 10:28 UTC, 0307kwon commented on frontend/src/components/LargeFeedCard/LargeFeedCard.tsx
> +            onError={(event: SyntheticEvent<HTMLImageElement>) => {
이미지 깨짐 방지입니닷!

2021-08-31 10:28 UTC, 0307kwon commented on frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
>    });
isLoading이 스켈레톤 때문에 필요했었는데 지금 스켈레톤을 적용하지 않아서 잠깐 뺐습니다~!

2021-08-31 10:28 UTC, 0307kwon commented on frontend/src/components/RegularFeedCard/RegularFeedCard.stories.tsx
> +export const Default = () => <RegularFeedCard feed={mockFeed} />;
RegularCard -> RegularFeedCard
LargeCard -> LargeFeedCard
로 파일 네임을 바꾸어주었는데 feed를 붙인 이유가 너무 일반적인 네이밍이라서 바꿔주었습니다.
prop으로 feed까지 받고 있는데 그냥 카드라고 하기에는 로직이 너무많이 들어가더라구용!

2021-08-31 10:28 UTC, 0307kwon commented on frontend/src/components/HotFeedsContent/HotFeedsContent.tsx
> +              <LargeFeedCard feed={feed} />
이제 FeedCard이므로 Avatar 컴포넌트를 LargeFeedCard 안으로 넣어주고
Link 컴포넌트 역시 안으로 넣어주었습니다.

2021-08-31 10:28 UTC, 0307kwon commented on frontend/src/commonStyles.ts
> +`;
공통으로 사용할 수 있게 빼냈는데 사용할지는....? 아직은 잘모르겠습니닷

2021-08-31 11:30 UTC, zigsong requested changes
오랜만의 리뷰 남겼습니다!!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/commonStyles.ts
> +`;
오 저도 이런거 원했는데 통했네요 좋아용

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/BaseLayout/BaseLayout.styles.tsx
> +  }
breakpoint에 desktop!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/BaseLayout/BaseLayout.tsx
> +      <BaseLayoutMain>{children}</BaseLayoutMain>
👍👍

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/Header/Header.tsx
> +import { Link, NavLink } from 'react-router-dom';
위로 옮겨주세요!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/Header/Header.tsx
> +            <LogoSimple height="100%" />
왜 어디는 `width`고 어디는 `height`가 됐을까요? 👀

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/HotFeedsContent/HotFeedsContent.styles.ts
> +  transform: translateX(calc(-300px * var(--r) - 40px));
이걸 계속 가져가는구나..!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/HotFeedsContent/HotFeedsContent.tsx
> +              <LargeFeedCard feed={feed} />
아하 좋아요~!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/LargeFeedCard/LargeFeedCard.tsx
> +            onError={(event: SyntheticEvent<HTMLImageElement>) => {
오 `onError`라는 속성도 있었군요 좋네요!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/RecentFeedsContent/RecentFeedsContent.styles.ts
> +  grid-gap: 1rem;
그리드 좋아용

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/RecentFeedsContent/RecentFeedsContent.tsx
>    });
앗 제가 만들면서 다시 넣어놀게용~!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/components/RegularFeedCard/RegularFeedCard.stories.tsx
> +export const Default = () => <RegularFeedCard feed={mockFeed} />;
아하 좋습니다!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/constants/common.ts
> +
height를 따로 상수로 빼준 이유가 있나요?

2021-08-31 11:30 UTC, zigsong commented on frontend/src/constants/common.ts
> +
그것도 header만!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/constants/common.ts
> +} as const;
요거는 왜 `as const`를 붙여주셨나요? 사용하는 곳에서 타입에러 나나요?

2021-08-31 11:30 UTC, zigsong commented on frontend/src/pages/Home/Home.tsx
> +      <>
이 `<>`태그는 없어도 될듯?!

2021-08-31 11:30 UTC, zigsong commented on frontend/src/pages/SearchResult/SearchResult.tsx
> +import { useLocation } from 'react-router-dom';
위쪽으로 import문 분리해주세욤

2021-08-31 11:36 UTC, zigsong commented
그리고 Home의 HotToys들은 아예 3개만 딱 보이게끔 카드 각각의 크기를 키우던가, 4개 딱 보이게끔 조금 줄이던가 하면 좋을 것 같아요!
'진행중'이나 '전시중' 애들은 딱 맞게 떨어지는데 쟤네(Hot Toy)만 뭔가 애매하게 끊긴 느낌? 

그리고 걔네들을 carousel로 넘길 수 있다는 게 티가 안 난다면,
![image](https://user-images.githubusercontent.com/44080404/131495665-62ef3532-e08d-4659-a44d-d326b3687852.png)
요런 점들을 붙여주면... (귀찮겠지만...) 좋아보일듯??? 

추가적으로 Home에서 헤더와 컨텐츠의 거리가 쫌 쫍아보여요!

2021-08-31 15:20 UTC, 0307kwon commented on frontend/src/components/Header/Header.tsx
> +            <LogoSimple height="100%" />
로고는 헤더 height랑 맞추기위해서 height 속성만 넣어주고 width는 자동으로 들어가게 했습니닷!

2021-08-31 15:32 UTC, 0307kwon commented on frontend/src/constants/common.ts
> +
![image](https://user-images.githubusercontent.com/48755175/131531825-f1b17c19-a42e-4fff-b7b4-e0effa30aaee.png)
헤더 크기에 따라 정해지는 UI 요소들이 많더라구요...! 상수로 관리하고 싶은데 그냥 객체 리터럴 형태말고 상수 하나로 관리할까용?

2021-08-31 15:39 UTC, 0307kwon commented on frontend/src/constants/common.ts
> +} as const;
![image](https://user-images.githubusercontent.com/48755175/131532125-2a457b36-e0f0-4692-bde9-8d893aecd9ae.png)
이거는 그냥 문자열 리터럴 타입으로 추론하고 싶어서 해놓긴 했는데 그냥 DEFAULT_IMG_URL로 객체 이름을 바꿀까용?
지금보니 딱히 필요는 없을듯....ㅋㅋㅋ

2021-09-01 07:11 UTC, 0307kwon commented
전부 반영했씁니다~!!~!~
![image](https://user-images.githubusercontent.com/48755175/131628043-6e2e073d-90c4-4b7c-bff1-3f54119e5780.png)

2021-09-01 07:15 UTC, zigsong reviewed
일단은 빠르게 리뷰 남겼슴~!

2021-09-01 07:15 UTC, zigsong commented on frontend/src/components/Header/Header.styles.ts
> +import styled, { keyframes } from 'styled-components';
import문 위로 옮겨주세용~!

2021-09-01 07:15 UTC, zigsong commented on frontend/src/components/HotFeedsContent/HotFeedsContent.styles.ts
> +  );
장인정신...

2021-09-01 07:15 UTC, zigsong commented on frontend/src/components/HotFeedsContent/HotFeedsContent.tsx
>  import Styled, { CarouselArrowButton } from './HotFeedsContent.styles';
style import를 맨 밑으로 빼주세용~!

2021-09-01 07:15 UTC, zigsong commented on frontend/src/components/RecentFeedsContent/RecentFeedsContent.styles.ts
> +import styled from 'styled-components';
import문 위로 올려주세요~!

2021-09-01 07:15 UTC, zigsong commented on frontend/src/components/RegularFeedCard/RegularFeedCard.tsx
> +import { Link } from 'react-router-dom';
import 위로 올려주세용~!

2021-09-01 07:15 UTC, zigsong commented on frontend/src/constants/common.ts
> +
아하 그런 이유라면 납득이에요 지금 좋아요~!

2021-09-01 07:15 UTC, zigsong commented on frontend/src/constants/common.ts
> +} as const;
ㅋㅋㅋㅋ 그냥 두어도 괜찮을 것 같음!!

2021-09-01 07:15 UTC, zigsong commented on frontend/src/constants/mediaQuery.ts
> +  DESKTOP: `screen and (max-width: ${BREAK_POINTS.DESKTOP})`,
DESKTOP 굳굳ㄱ

2021-09-01 07:32 UTC, 0307kwon commented
반영해씁니답~~~! 👍😁

2021-09-01 07:32 UTC, merged