feat: 페이지네이션 구현
woowacourse-teams/2021-nolto pull request #494
Opened 2021-09-02 03:41 UTC by PapimonLikelion

## 작업 내용
- 요청 양식
`GET: /feeds/recent2?step=progress&help=true&nextFeedId=2&countPerPage=5`
    - 모든 파라미터는 생략 가능
        - countPerPage 생략 시 기본으로 15개로 지정

- 응답 양식
```
{
    "feeds": [
        {
            "author": {
                "id": 1,
                "nickname": "미키",
                "imageUrl": "https://dksykemwl00pf.cloudfront.net/amazzi.jpeg"
            },
            "id": 2,
            "title": "title2",
            "content": "content2",
            "step": "COMPLETE",
            "sos": false,
            "thumbnailUrl": "https://dksykemwl00pf.cloudfront.net/KakaoTalk_Photo_2021-07-19-14-25-01.png"
        },
        {
            "author": {
                "id": 1,
                "nickname": "미키",
                "imageUrl": "https://dksykemwl00pf.cloudfront.net/amazzi.jpeg"
            },
            "id": 1,
            "title": "title1",
            "content": "content1",
            "step": "PROGRESS",
            "sos": true,
            "thumbnailUrl": "https://dksykemwl00pf.cloudfront.net/KakaoTalk_Photo_2021-07-19-14-25-01.png"
        }
    ],
    "nextFeedId": null
}
```
- RequestParam의 유효성을 검증하기 위해서 FeedController에 `@Validated` 추가
    - 해당 제약 조건을 만족하지 않는다면, ConstraintViolationException 예외 발생
    - 해당 ControllerAdvice에 해당 예외 잡아둠
    - 예외 메시지에 "FeedController.검사한 메서드"까지 포함되어 나옴

## 주의사항
- 현재 API 명명이 `/recent2`로 되어있음. 나중에 수정 요망
- `/recent2` 에서만 step과 help를 분리함 
    - `/search`에서는 filter로 여전히 SOS, PROGRESS, COMPLETE 구분 중
- 문서화 및 `/recent`로의 api 변경은 dev 서버에서 검증 이후에 진행 예정

2021-09-02 20:29 UTC, Gomding requested changes
페이지 구현한 코드 잘봤습니다 😃 
코멘트에도 남겼듯이 현재 N+1 조회가 발생하고 있어요!

2021-09-02 20:29 UTC, Gomding commented on backend/src/main/java/com/wooteco/nolto/feed/domain/repository/FeedRepository.java
> +    List<Feed> findWithHelp(@Param("steps") EnumSet<Step> steps, @Param("help") Boolean help, @Param("feedId") Long feedId, Pageable pageable);
현재 조회시 N+1 쿼리가 날아가고 있어요 😱 

피드를 3개 조회해온다고 하면 다음 순서로 쿼리가 날아가요
* 피드 (3,2,1) 인 리스트를 가져옴  -> select 1회 발생
* 각 피드에 대한 author 가 Lazy Loading이 일어나면서 -> 피드 개수만큼 User select n회 발생
    * 피드3에 대한 author 조회
    * 피드2에 대한 author 조회
    * 피드1에 대한 author 조회

``` java
    @Query(value = "select distinct feed " + // distinct 카테시안 곱 방지
            "from Feed as feed " +
            "join fetch feed.author u " + // join fetch 추가
            "where feed.id <= :feedId and feed.step in :steps " +
            "order by feed.createdDate desc, feed.id desc")
    List<Feed> findWithoutHelp(@Param("steps") EnumSet<Step> steps, @Param("feedId") Long feedId, Pageable pageable);

    @Query(value = "select distinct feed " +
            "from Feed as feed " +
            "join fetch feed.author u " +
            "where feed.id <= :feedId and feed.step in :steps and feed.isSos =:help " +
            "order by feed.createdDate desc, feed.id desc")
    List<Feed> findWithHelp(@Param("steps") EnumSet<Step> steps, @Param("help") Boolean help, @Param("feedId") Long feedId, Pageable pageable);
```

2021-09-02 23:32 UTC, NewWisdom approved these changes
포조포조 ~
수고 많았습니다 !!! 
페이지네이션 대박스 멋져요!!!! 
테스트까지 꼼꼼하게 호라닥 짜주셨네요 👏
수고 많으셨습니다 :)
보면서 한가지 제안 해보았는데 굳이 반영하지 않아도 좋습니다!! ㅎㅎ

2021-09-02 23:32 UTC, NewWisdom commented on backend/src/main/java/com/wooteco/nolto/feed/domain/repository/FeedRepository.java
> +    List<Feed> findWithHelp(@Param("steps") EnumSet<Step> steps, @Param("help") Boolean help, @Param("feedId") Long feedId, Pageable pageable);
오홋 찰리 말대로 `join fetch`를 사용해도 좋겠네용

2021-09-02 23:32 UTC, NewWisdom commented on backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
> +                                                                     @RequestParam(required = false, defaultValue = "15") @Valid @Pattern(regexp = "^[1-9][0-9]*$", message = "자연수만 가능합니다.") String cou
꼼꼼한 예외처리 개쩐다 멋져요 👏
흠 컨트롤러에서 RequestParam이 많아지고 예외처리가 있어 어떻게 해볼 수 없을까 찾아봤는데
[Spring 어플리케이션에서 Request Parameter를 모델 클래스로 처리하기](https://bum752.github.io/posts/Spring-%EC%96%B4%ED%94%8C%EB%A6%AC%EC%BC%80%EC%9D%B4%EC%85%98%EC%97%90%EC%84%9C-Request-Parameter%EB%A5%BC-%EB%AA%A8%EB%8D%B8-%ED%81%B4%EB%9E%98%EC%8A%A4%EB%A1%9C-%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0/)
DTO로도 처리가 가능하다고 하네요!!! (저도 처음 알았어요)
이러면 저 깔끔해질 것 같은데 단점을 생각해보자면 컨트롤러에서 해당 dto가 파람으로 들어오는지 알아채기 어렵다?가 될 수 있을 것 같네요 ! (get 메서드면 파람으로 들어오겠구나 인지할 수 있을 것 같기도.?)
저도 그냥 한번 제안해보는거라, 스루해도 좋습니다 ㅎㅎㅎ

2021-09-02 23:32 UTC, NewWisdom commented on backend/src/test/java/com/wooteco/nolto/feed/application/FeedServiceTest.java
> +        // given
테스트까지 꼼꼼하게 멋져여 👏

2021-09-03 00:01 UTC, PapimonLikelion commented on backend/src/main/java/com/wooteco/nolto/feed/domain/repository/FeedRepository.java
> +    List<Feed> findWithHelp(@Param("steps") EnumSet<Step> steps, @Param("help") Boolean help, @Param("feedId") Long feedId, Pageable pageable);
세상에 그러네요! DB 접근 한번 줄인다고 고민했었는데 N번 더 나갔네 😅😅

2021-09-03 04:12 UTC, bosl95 commented on backend/src/main/java/com/wooteco/nolto/feed/ui/FeedController.java
> +                                                                     @RequestParam(required = false, defaultValue = "15") @Valid @Pattern(regexp = "^[1-9][0-9]*$", message = "자연수만 가능합니다.") String cou
우선 결론부터 말하자면 아마찌의 의견에 동의합니다!

현재 recentResponse()에서만 해당 쿼리 파라미터들을 사용하고 있어요!
그렇기에 저렇게 나열해줌으로써 한눈에 확인 가능하다는 장점이 있다고 생각했습니다.

하지만 추후에 수정될 search도 마찬가지로 위의 쿼리 파람들이 사용될텐데, 저 길고긴 queryparam이 중복될 생각하니 아찔하네요!
그런 의미에서 DTO로 묶어주는 방향으로 진행하는 것에 동의합니당당

2021-09-03 07:04 UTC, merged